### ISSUE TITLE
implementation of a database and first import 

### ISSUE THREAD

**Issue by martin-huemmer** [coronapolation/coronapolation#2]
Data source for corona data can be found here: 

https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0/data

**Comment by tmsmr** [comment]
prototype for importer finished: https://github.com/coronapolation/coronapolation/tree/master/datafetcher

initial db for tests on server: ~/coronapolation.sqlite

**Comment by tmsmr** [comment]
instead of dropping the db, rows are updated now: https://github.com/coronapolation/coronapolation/commit/5af8291df09c38a3c5dc564665bdcf6e9d20a086
